apiVersion: apps/v1
kind: Deployment
metadata:
  name: roshu1622-deploy1
  labels:
    app: roshu1622-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: roshu1622-app1
  template:
    metadata:
      labels:
        app: roshu1622-app1
    spec:
      containers:
      - name: roshu1622-container1
        image: roshu1622/roshu1622-app1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: roshu1622-np-service1
  labels:
    app: roshu1622-app1
spec:
  selector:
    app: roshu1622-app1

  type: NodePort
  ports:
  - nodePort: 31002
    port: 8080
    targetPort: 8080
